# Generated by Django 4.2.7 on 2024-02-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nome del Brand",
                    ),
                ),
                ("image", models.TextField(verbose_name="Immagine del Brand")),
                (
                    "brand_online_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL del Brand Online",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Trattori", "Trattori"),
                            ("Attrezzature", "Attrezzature"),
                            ("Entrambi", "Entrambi"),
                        ],
                        default="Trattori",
                        max_length=12,
                        verbose_name="Categoria del Brand",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("PDF", "PDF"),
                            ("Entrambi", "Entrambi"),
                        ],
                        default="Online",
                        max_length=12,
                        verbose_name="Typo del Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="BrandOnlineCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=256, verbose_name="Username del brand online"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=256, verbose_name="Password del brand online"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brands.brand",
                        verbose_name="Brand della credenziale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credenziale del Brand",
                "verbose_name_plural": "Credenziali dei Brand",
            },
        ),
        migrations.CreateModel(
            name="BrandFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.TextField(verbose_name="File del Brand")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrizione del File"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brands.brand",
                        verbose_name="Brand del File",
                    ),
                ),
            ],
            options={
                "verbose_name": "File del Brand",
                "verbose_name_plural": "Files dei Brand",
            },
        ),
    ]
