# Generated by Django 4.2.7 on 2024-02-29 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("surname", models.CharField(default="", max_length=255)),
                ("fiscal_code", models.CharField(default="", max_length=16)),
                ("phone_number", models.CharField(default="", max_length=10)),
                ("nation", models.CharField(default="", max_length=255)),
                ("region", models.CharField(default="", max_length=255)),
                ("council", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clienti",
            },
        ),
    ]
